# Generated by Django 3.0.5 on 2020-10-31 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInventoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, editable=False, max_length=255)),
                ('book_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('total_book_count', models.IntegerField(blank=True, null=True)),
                ('book_borrowed', models.IntegerField(blank=True, null=True)),
                ('book_available', models.IntegerField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Creation timestamp')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookBorrowDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Creation timestamp')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_borrow_rel', to='book_inventory_management.BookInventoryDetail')),
            ],
        ),
    ]
