# Generated by Django 3.0.5 on 2020-10-31 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrowdetail',
            name='borrowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_borrow_rel', to=settings.AUTH_USER_MODEL),
        ),
    ]
